#!/bin/bash
# IntelliLog-AI Quick Command Reference

echo "🚀 IntelliLog-AI Quick Command Reference"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "📋 BACKEND COMMANDS"
echo "───────────────────────────────────────────────────────────────"
echo ""
echo "Start Backend Server:"
echo "  cd src/backend"
echo "  python -m uvicorn app.main:application --reload --port 8000"
echo ""
echo "View API Docs (after starting):"
echo "  Swagger UI: http://localhost:8000/docs"
echo "  ReDoc:      http://localhost:8000/redoc"
echo ""
echo "Seed Database (first time):"
echo "  cd src/backend"
echo "  python -m src.backend.app.db.seed"
echo ""
echo "Run Migrations:"
echo "  cd src/backend"
echo "  alembic upgrade head"
echo ""
echo "───────────────────────────────────────────────────────────────"
echo "🎨 FRONTEND COMMANDS"
echo "───────────────────────────────────────────────────────────────"
echo ""
echo "Start Development Server:"
echo "  cd src/frontend"
echo "  npm install         # First time only"
echo "  npm run dev"
echo ""
echo "Build for Production:"
echo "  cd src/frontend"
echo "  npm run build"
echo ""
echo "Run Tests:"
echo "  cd src/frontend"
echo "  npm test"
echo ""
echo "Lint Code:"
echo "  cd src/frontend"
echo "  npm run lint"
echo ""
echo "───────────────────────────────────────────────────────────────"
echo "🔐 AUTHENTICATION TESTING"
echo "───────────────────────────────────────────────────────────────"
echo ""
echo "Test Login Endpoint:"
echo "  curl -X POST http://localhost:8000/api/v1/auth/login \\"
echo "    -H \"Content-Type: application/x-www-form-urlencoded\" \\"
echo "    -d \"username=admin@intellilog.ai&password=Admin@123\""
echo ""
echo "Test Protected Endpoint (use access_token from login):"
echo "  curl -X GET http://localhost:8000/api/v1/auth/me \\"
echo "    -H \"Authorization: Bearer {access_token}\""
echo ""
echo "Test Token Refresh:"
echo "  curl -X POST http://localhost:8000/api/v1/auth/refresh \\"
echo "    -H \"Authorization: Bearer {refresh_token}\""
echo ""
echo "───────────────────────────────────────────────────────────────"
echo "🧪 DATABASE COMMANDS"
echo "───────────────────────────────────────────────────────────────"
echo ""
echo "Connect to Database:"
echo "  psql -U postgres -d intellog"
echo ""
echo "View Users:"
echo "  SELECT id, email, full_name, role FROM users;"
echo ""
echo "Create New Migration:"
echo "  alembic revision --autogenerate -m \"description\""
echo ""
echo "Reset Database (WARNING: deletes all data):"
echo "  alembic downgrade base"
echo "  alembic upgrade head"
echo "  python -m src.backend.app.db.seed"
echo ""
echo "───────────────────────────────────────────────────────────────"
echo "📊 COMMON URLS"
echo "───────────────────────────────────────────────────────────────"
echo ""
echo "Landing Page:     http://localhost:5173"
echo "Login Page:       http://localhost:5173/auth/login"
echo "Signup Page:      http://localhost:5173/auth/signup"
echo "Dashboard:        http://localhost:5173/dashboard"
echo ""
echo "API Docs:         http://localhost:8000/docs"  
echo "Health Check:     http://localhost:8000/health"
echo ""
echo "───────────────────────────────────────────────────────────────"
echo "🔑 DEFAULT CREDENTIALS"
echo "───────────────────────────────────────────────────────────────"
echo ""
echo "Email:    admin@intellilog.ai"
echo "Password: Admin@123"
echo ""
echo "───────────────────────────────────────────────────────────────"
echo "🐛 DEBUGGING & LOGS"
echo "───────────────────────────────────────────────────────────────"
echo ""
echo "Backend Logs (in terminal):"
echo "  See output in the terminal running uvicorn"
echo "  Enable DEBUG in src/backend/app/core/config.py"
echo ""
echo "Frontend Console:"
echo "  F12 → Console tab (browser developer tools)"
echo "  Look for auth state and API call details"
echo ""
echo "Database Logs:"
echo "  Check PostgreSQL logs: /var/log/postgresql/"
echo ""
echo "───────────────────────────────────────────────────────────────"
echo "🚢 DOCKER COMMANDS"
echo "───────────────────────────────────────────────────────────────"
echo ""
echo "Build & Start (docker-compose):"
echo "  docker-compose up --build"
echo ""
echo "Stop Services:"
echo "  docker-compose down"
echo ""
echo "View Logs:"
echo "  docker-compose logs -f"
echo ""
echo "Execute Command in Container:"
echo "  docker-compose exec backend python -m src.backend.app.db.seed"
echo ""
echo "───────────────────────────────────────────────────────────────"
echo "⚡ ENVIRONMENT VARIABLES"
echo "───────────────────────────────────────────────────────────────"
echo ""
echo "Frontend (.env):"
echo "  VITE_API_URL=http://localhost:8000/api/v1"
echo "  VITE_ENV=development"
echo ""
echo "Backend (.env or system):"
echo "  SECRET_KEY=your-secret-key-here"
echo "  DATABASE_URL=postgresql://user:pass@localhost/intellog"
echo "  POSTGRES_SERVER=localhost"
echo "  POSTGRES_PORT=5433"
echo "  POSTGRES_DB=intellog"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "✨ For detailed setup guide, see: SAAS_SETUP_GUIDE.md"
echo "📖 For full documentation, see: IMPLEMENTATION_SUMMARY.md"
echo ""
