"""Create traffic_patterns table for historical traffic aggregation.

Revision ID: 2026_03_19_traffic_patterns
Revises: bb091f6b76c8_add_warehouse_id
Create Date: 2026-03-19 14:00:00.000000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2026_03_19_traffic_patterns"
down_revision = "bb091f6b76c8_add_warehouse_id"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "traffic_patterns",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("zone_origin", sa.String(length=50), nullable=False),
        sa.Column("zone_dest", sa.String(length=50), nullable=False),
        sa.Column("weekday", sa.Integer(), nullable=False),
        sa.Column("hour", sa.Integer(), nullable=False),
        sa.Column("avg_travel_time_min", sa.Float(), nullable=True),
        sa.Column("std_travel_time_min", sa.Float(), nullable=True),
        sa.Column("avg_traffic_ratio", sa.Float(), nullable=False, server_default="1.0"),
        sa.Column("std_traffic_ratio", sa.Float(), nullable=True),
        sa.Column("avg_distance_meters", sa.Float(), nullable=True),
        sa.Column("sample_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column(
            "last_updated",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_traffic_zone_origin", "traffic_patterns", ["zone_origin"])
    op.create_index("idx_traffic_zone_dest", "traffic_patterns", ["zone_dest"])
    op.create_index("idx_traffic_last_updated", "traffic_patterns", ["last_updated"])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_traffic_last_updated", table_name="traffic_patterns")
    op.drop_index("idx_traffic_zone_dest", table_name="traffic_patterns")
    op.drop_index("idx_traffic_zone_origin", table_name="traffic_patterns")
    op.drop_table("traffic_patterns")
