"""Add explanation_json column to delivery_feedback table.

Revision ID: 2026_03_20_explanations
Revises: 2026_03_19_traffic_patterns
Create Date: 2026-03-20 15:00:00.000000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2026_03_20_explanations"
down_revision = "2026_03_19_traffic_patterns"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "delivery_feedback",
        sa.Column("explanation_json", sa.String(), nullable=True),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("delivery_feedback", "explanation_json")
