"""Initial migration

Revision ID: 9fd3f9ce2901
Revises: 
Create Date: 2026-02-04 11:31:29.621754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9fd3f9ce2901'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('plan', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('drivers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('current_lat', sa.Float(), nullable=True),
    sa.Column('current_lng', sa.Float(), nullable=True),
    sa.Column('vehicle_capacity', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('routes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('total_distance_km', sa.Float(), nullable=True),
    sa.Column('total_duration_min', sa.Float(), nullable=True),
    sa.Column('geometry_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('driver_id', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('orders', sa.Column('order_number', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('customer_name', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('delivery_address', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('lng', sa.Float(), nullable=False))
    op.add_column('orders', sa.Column('weight', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('time_window_start', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('time_window_end', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('status', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('tenant_id', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('route_id', sa.String(), nullable=True))
    op.alter_column('orders', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index('idx_orders_geom', table_name='orders', postgresql_using='gist')
    op.drop_index('ix_orders_id', table_name='orders')
    op.drop_index('ix_orders_order_id', table_name='orders')
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.create_foreign_key(None, 'orders', 'routes', ['route_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'tenants', ['tenant_id'], ['id'])
    op.drop_column('orders', 'order_type')
    op.drop_column('orders', 'created_at')
    op.drop_column('orders', 'order_id')
    op.drop_column('orders', 'order_time')
    op.drop_column('orders', 'traffic')
    op.drop_column('orders', 'weather')
    op.drop_column('orders', 'geom')
    op.drop_column('orders', 'lon')
    op.drop_column('orders', 'distance_km')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('distance_km', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('lon', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('geom', sa.NullType(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('weather', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('traffic', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('order_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('order_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('order_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.create_index('ix_orders_order_id', 'orders', ['order_id'], unique=True)
    op.create_index('ix_orders_id', 'orders', ['id'], unique=False)
    op.create_index('idx_orders_geom', 'orders', ['geom'], unique=False, postgresql_using='gist')
    op.alter_column('orders', 'id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('orders', 'route_id')
    op.drop_column('orders', 'tenant_id')
    op.drop_column('orders', 'status')
    op.drop_column('orders', 'time_window_end')
    op.drop_column('orders', 'time_window_start')
    op.drop_column('orders', 'weight')
    op.drop_column('orders', 'lng')
    op.drop_column('orders', 'delivery_address')
    op.drop_column('orders', 'customer_name')
    op.drop_column('orders', 'order_number')
    op.drop_table('routes')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('drivers')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
