"""Add warehouse_id

Revision ID: bb091f6b76c8
Revises: 9fd3f9ce2901
Create Date: 2026-02-12 19:06:12.493075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb091f6b76c8'
down_revision: Union[str, Sequence[str], None] = '9fd3f9ce2901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('service_radius_km', sa.Float(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=True),
    sa.Column('driver_id', sa.String(), nullable=True),
    sa.Column('warehouse_id', sa.String(), nullable=True),
    sa.Column('predicted_eta_min', sa.Float(), nullable=True),
    sa.Column('actual_delivery_min', sa.Float(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('drivers', sa.Column('warehouse_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'drivers', 'warehouses', ['warehouse_id'], ['id'])
    op.add_column('orders', sa.Column('warehouse_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'orders', 'warehouses', ['warehouse_id'], ['id'])
    op.add_column('routes', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('routes', sa.Column('warehouse_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'routes', 'warehouses', ['warehouse_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'routes', type_='foreignkey')
    op.drop_column('routes', 'warehouse_id')
    op.drop_column('routes', 'updated_at')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'warehouse_id')
    op.drop_constraint(None, 'drivers', type_='foreignkey')
    op.drop_column('drivers', 'warehouse_id')
    op.drop_table('delivery_logs')
    op.drop_table('warehouses')
    # ### end Alembic commands ###
